# Generated by Django 5.0.4 on 2024-04-09 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custum_fields', '0002_alter_citymodal_country_remove_statemodal_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statemodal',
            name='country',
        ),
        migrations.AddField(
            model_name='statemodal',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='custum_fields.countrymodel'),
            preserve_default=False,
        ),
    ]
