# Generated by Django 5.0.4 on 2024-04-09 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custum_fields', '0003_remove_statemodal_country_statemodal_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodal',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custum_fields.statemodal'),
        ),
        migrations.AlterField(
            model_name='statemodal',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custum_fields.countrymodel'),
        ),
    ]
