# Generated by Django 5.0.4 on 2024-04-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custum_fields', '0004_alter_citymodal_state_alter_statemodal_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymodel',
            name='flags',
            field=models.ImageField(default=1, upload_to='country_flags'),
            preserve_default=False,
        ),
    ]
