# Generated by Django 5.0.4 on 2024-04-09 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('custum_fields', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('profile_photo', models.ImageField(upload_to='user_profile_photo')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('updated_time', models.TimeField(auto_now=True)),
                ('verification_code', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=False)),
                ('forgot', models.IntegerField(blank=True, null=True)),
                ('is_forgot', models.BooleanField(default=False)),
                ('Country_code_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custum_fields.countrycode')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custum_fields.citymodal')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custum_fields.countrymodel')),
                ('groups', models.ManyToManyField(related_name='groups', related_query_name='groups', to='auth.group')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custum_fields.statemodal')),
                ('user_permissions', models.ManyToManyField(related_name='permissions', related_query_name='permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
